[package]
org = "ballerina"
name = "regex"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["regex", "string", "regular expressions"]
repository = "https://github.com/ballerina-platform/module-ballerina-regex"
license = ["Apache-2.0"]
distribution = "2201.0.0"
