[package]
org = "ballerina"
name = "regex"
version = "1.3.1"
authors = ["Ballerina"]
keywords = ["regex", "string", "regular expressions"]
repository = "https://github.com/ballerina-platform/module-ballerina-regex"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"
